version: '3'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - .:/var/www/html

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - .:/var/www/html

  ch_server:
    image: yandex/clickhouse-server
    container_name: ch_server
    ports:
      - "8123:8123"
    volumes:
      - ./docker/db/clickhouse:/var/lib/clickhouse
  myapp_tasks:
    image: php
    restart: always
    command:
      - php /app/telega.php